name: Build Blog

on:
  push:
    branches:
      - main
    paths:
      - 'posts_md/**.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install marked

      - name: Convert Markdown to HTML
        run: |
          for file in posts_md/*.md; do
            if [ -f "$file" ]; then
              filename=$(basename -- "$file")
              slug="\${filename%.*}"
              npx marked -i "$file" -o "posts/\${slug}.html"
            fi
          done
      
      - name: Generate index.html
        run: node generate-index.js

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "build: update blog posts and index"
          branch: main
          file_pattern: 'posts/**.html index.html'
